### ISSUE TITLE
working on similar idea

### ISSUE THREAD

**Issue by unional** [blakeembrey/decorator-memoize-one#1]
Hi Blake,

Hopes you are doing well. Haven't cross-path with you for a while.
Saw you created this repo.
I was working on something similar. You may want to check it out: [`komondor`](https://github.com/unional/komondor).

I was in the process of rewriting it in v7 to expand its feature.
Taking time on that one. 🌷

**Comment by blakeembrey** [comment]
I don't know if this module overlaps with functionality, this is pretty simple code - I mostly just wanted a simple `memoize` for TypeScript class methods and don't care to maintain a history of memoize. I only needed the most recent matching fetch since query for a session context user with the same pool will mean avoiding unnecessary DB calls, stuff like that.

But `komondor` seems pretty interesting if I'm reading it correctly. Is the idea that it's kind of a mix between a mock and a snapshot of the result? On the first run it'll make a snapshot of the result and on subsequent tests it'll return the mock? That'd solve a use-case I've been hacking around myself into test cases and persisting data into files.

**Comment by unional** [comment]
I see. 

> Is the idea that it's kind of a mix between a mock and a snapshot of the result?

It is something similar. It is more like a record/replay mechanism.
It saves the behavior of the calls during `save` mode and replays it during `simulate` mode.
When you finish with your test, you will typically run the code in `simulate` mode.
You can think of it as a mock, but without manually setting up the behavior.

Another key feature is that you can change the mode globally so that you can turn all or some of your test back to `live` mode to test against the real thing.
It is used to do system/integration tests when external service changes.


EDIT: btw this was the idea I wanted to tell you about a while back through email. I want to get it to v7 first but...... 😛
